from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(893, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 881, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.dasboard_tab = QtWidgets.QWidget()
        self.dasboard_tab.setObjectName("dasboard_tab")
        self.label = QtWidgets.QLabel(self.dasboard_tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.dasboard_tab)
        self.label_2.setGeometry(QtCore.QRect(10, 66, 44, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.new_book_btn = QtWidgets.QPushButton(self.dasboard_tab)
        self.new_book_btn.setGeometry(QtCore.QRect(10, 37, 75, 23))
        self.new_book_btn.setObjectName("new_book_btn")
        self.widget = QtWidgets.QWidget(self.dasboard_tab)
        self.widget.setGeometry(QtCore.QRect(9, 94, 861, 441))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.issue_books_table = QtWidgets.QTableWidget(self.widget)
        self.issue_books_table.setColumnCount(8)
        self.issue_books_table.setObjectName("issue_books_table")
        self.issue_books_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.issue_books_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.issue_books_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.issue_books_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.issue_books_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.issue_books_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.issue_books_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.issue_books_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.issue_books_table.setHorizontalHeaderItem(7, item)
        self.horizontalLayout.addWidget(self.issue_books_table)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.delete_issued = QtWidgets.QPushButton(self.widget)
        self.delete_issued.setObjectName("delete_issued")
        self.verticalLayout.addWidget(self.delete_issued)
        self.edit_issued = QtWidgets.QPushButton(self.widget)
        self.edit_issued.setObjectName("edit_issued")
        self.verticalLayout.addWidget(self.edit_issued)
        self.refresh_issued = QtWidgets.QPushButton(self.widget)
        self.refresh_issued.setObjectName("refresh_issued")
        self.verticalLayout.addWidget(self.refresh_issued)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.unissued_books_table = QtWidgets.QTableWidget(self.widget)
        self.unissued_books_table.setColumnCount(8)
        self.unissued_books_table.setObjectName("unissued_books_table")
        self.unissued_books_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.unissued_books_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.unissued_books_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.unissued_books_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.unissued_books_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.unissued_books_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.unissued_books_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.unissued_books_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.unissued_books_table.setHorizontalHeaderItem(7, item)
        self.horizontalLayout_2.addWidget(self.unissued_books_table)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.delete_unissued = QtWidgets.QPushButton(self.widget)
        self.delete_unissued.setObjectName("delete_unissued")
        self.verticalLayout_2.addWidget(self.delete_unissued)
        self.edit_unissued = QtWidgets.QPushButton(self.widget)
        self.edit_unissued.setObjectName("edit_unissued")
        self.verticalLayout_2.addWidget(self.edit_unissued)
        self.refresh_unissued = QtWidgets.QPushButton(self.widget)
        self.refresh_unissued.setObjectName("refresh_unissued")
        self.verticalLayout_2.addWidget(self.refresh_unissued)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.dasboard_tab, "")
        self.find_tab = QtWidgets.QWidget()
        self.find_tab.setObjectName("find_tab")
        self.widget1 = QtWidgets.QWidget(self.find_tab)
        self.widget1.setGeometry(QtCore.QRect(10, 20, 731, 511))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.search_input = QtWidgets.QLineEdit(self.widget1)
        self.search_input.setObjectName("search_input")
        self.horizontalLayout_4.addWidget(self.search_input)
        self.search_btn = QtWidgets.QPushButton(self.widget1)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_4.addWidget(self.search_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.search_table = QtWidgets.QTableWidget(self.widget1)
        self.search_table.setColumnCount(8)
        self.search_table.setObjectName("search_table")
        self.search_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(7, item)
        self.verticalLayout_5.addWidget(self.search_table)
        self.tabWidget.addTab(self.find_tab, "")
        self.all_books_tab = QtWidgets.QWidget()
        self.all_books_tab.setObjectName("all_books_tab")
        self.all_books_table = QtWidgets.QTableWidget(self.all_books_tab)
        self.all_books_table.setGeometry(QtCore.QRect(0, 80, 729, 478))
        self.all_books_table.setColumnCount(8)
        self.all_books_table.setObjectName("all_books_table")
        self.all_books_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.all_books_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_books_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_books_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_books_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_books_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_books_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_books_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_books_table.setHorizontalHeaderItem(7, item)
        self.refresh_btn = QtWidgets.QPushButton(self.all_books_tab)
        self.refresh_btn.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.refresh_btn.setObjectName("refresh_btn")
        self.label_6 = QtWidgets.QLabel(self.all_books_tab)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.all_books_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 893, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Actions"))
        self.label_2.setText(_translate("MainWindow", "Books"))
        self.new_book_btn.setText(_translate("MainWindow", "New Book"))
        self.label_4.setText(_translate("MainWindow", "Issued Books"))
        item = self.issue_books_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.issue_books_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.issue_books_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Discription"))
        item = self.issue_books_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ISBN"))
        item = self.issue_books_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Page Count"))
        item = self.issue_books_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Issued"))
        item = self.issue_books_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Author"))
        item = self.issue_books_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Year"))
        self.delete_issued.setText(_translate("MainWindow", "Delete"))
        self.edit_issued.setText(_translate("MainWindow", "Edit"))
        self.refresh_issued.setText(_translate("MainWindow", "Refresh"))
        self.label_3.setText(_translate("MainWindow", "Unissued Books"))
        item = self.unissued_books_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.unissued_books_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.unissued_books_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Discription"))
        item = self.unissued_books_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ISBN"))
        item = self.unissued_books_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Page Count"))
        item = self.unissued_books_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Issued"))
        item = self.unissued_books_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Author"))
        item = self.unissued_books_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Year"))
        self.delete_unissued.setText(_translate("MainWindow", "Delete"))
        self.edit_unissued.setText(_translate("MainWindow", "Edit"))
        self.refresh_unissued.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dasboard_tab), _translate("MainWindow", "Dashboard"))
        self.label_5.setText(_translate("MainWindow", "Searchn By Id "))
        self.search_btn.setText(_translate("MainWindow", "Search"))
        item = self.search_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.search_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.search_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Discription"))
        item = self.search_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ISBN"))
        item = self.search_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Page Count"))
        item = self.search_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Issued"))
        item = self.search_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Author"))
        item = self.search_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Year"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.find_tab), _translate("MainWindow", "Find"))
        item = self.all_books_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.all_books_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.all_books_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Discription"))
        item = self.all_books_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ISBN"))
        item = self.all_books_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Page Count"))
        item = self.all_books_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Issued"))
        item = self.all_books_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Author"))
        item = self.all_books_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Year"))
        self.refresh_btn.setText(_translate("MainWindow", "Refresh"))
        self.label_6.setText(_translate("MainWindow", "All Books"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.all_books_tab), _translate("MainWindow", "All Books"))
